version: '3'
services:
  mockup:
    build:
      context: ./
      dockerfile: DockerfileMaven
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APPLICATION_NAME=mockup
      - DATABASE_HOST=mongodb://mongodb:27017/mongoDbTest
      - SERVER_PORT=8080
      - WEB_LOG_LEVEL=debug
      - LOG_LEVEL=info
      - SECRET=RDTF67TY98U091PIO2KLEWDS.ASDY7891023SDhvbjnoijopk123.123213ctyfguiojmsad
      - REFRESH_TIME=7000
      - EXPIRED_TIME=8000
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017-27017
    environment:
      MONGO_INITDB_DATABASE: mockyup
